name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install
      run: make update
